name: restaurant_app
description: My first app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  bloc: ^8.1.2
  flutter_screenutil: ^5.9.0


  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached: ^1.6.1
  image: ^4.0.17
  shared_preferences: ^2.2.0
  flutter_bloc: ^8.1.3
  list_wheel_scroll_view_nls: ^0.0.3
  carousel_slider: ^4.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

