name: restaurant_app
description: My first app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2

  #responsive
  flutter_screenutil: ^5.9.0

  #animation for
  cube_transition_plus: ^2.0.1


  cupertino_icons: ^1.0.2

  #local storage
  shared_preferences: ^2.2.0

  #flutter bloc/cubit architecture
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  #carusel
  carousel_slider: ^4.2.1


  #firebase technology
  firebase_core: ^2.19.0
  firebase: ^9.0.3
  firebase_auth: ^4.9.0
  firebase_database: ^10.3.1

  lottie: ^2.7.0
  connectivity_plus: ^5.0.1

  # google map for
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  http: ^0.13.6
  polymaker: ^1.0.3
  geolocator: ^9.0.0
  flutter_compass: ^0.8.0
  flutter_polyline_points: ^1.0.0

  #link and phone
  url_launcher: ^6.2.1
  # id generator
  uuid: ^4.1.0
  #image cached
  cached_network_image: ^3.3.0
  cached: ^1.6.1
  image: ^4.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

